name: tiq_service_mob
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  http: ^1.5.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  printing: ^5.14.2
  pdf: ^3.11.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
